spring.application.name=theRealAstrologers

spring.datasource.url=jdbc:postgresql://localhost:5432/astrology_app


spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


gemini.api.key=AIzaSyCHJBmB_x1u5lLWhzUrInUDwcva4IP2hXU

my.app.SECRET_KEY =MySuperSecretKeyForTheRealAstrologersApp2026

jwt.EXPIRATION_TIME=86400000
